= muBoard Library for Arduino IDE =

This library allows to control muBoard (using STM8S207) peripherals using the Arduino IDE.
The custom muBoard was developed as a tool to simplify circuit and IC validation, as has
been in use since  

For more information about this library contact the author via Github/gicking

== License ==

Copyright (C) 2018 Georg Icking-Konert. All right reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
